#!/usr/bin/env bash
# Script to fix Nginx to listen on port 80

# Ensure Nginx is running
service nginx start

# Configure Nginx to listen on port 80
sed -i 's/80 default_server/80/g' /etc/nginx/sites-available/default
service nginx restart
